### ISSUE TITLE
Tighten story

### ISSUE THREAD

**Issue by peterdesmet** [stijnvanhoey/waterinfo-tidal-eel#2]
Did a quick review of the post. I would shorten it and focus on eel `A69-1601-52644` (Oliver) and her relation with the tides (and thus a use case for wateRinfo). Outline:

### Introduction @peterdesmet

- [x] wateRinfo
- [x] tracking network: video
- [x] eel Buttercup

### Favourite place @peterdesmet

- [x] residence time: simple **map** so user has some context geographically

### Route to the sea @peterdesmet

- [ ] **table** with all receivers passed + distance to sea (link to code how it was calculated)
- [ ] Mention how we add some labels for municipalities
- [x] **plot** cf https://github.com/stijnvanhoey/wateRinfo_post/blob/f99fe249a681a529e6ecc153ad57024e16f6f100/docs/figure/unnamed-chunk-10-1.png
- [x] Mention how eel is moving back and forth a lot

### Tidal data @peterdesmet

- [x] wateRinfo package
- [ ] **table** extended with _stations_ (no map)
- [x] Get tidal data
- [x] **plot** with tidal data for single station (no minima/maxima, no gray bars)

### Combining the two @stijnvanhoey

- [x] **plot** as described in #1

### Conclusion @peterdesmet

- [x] Advantage of using wateRinfo

**Comment by peterdesmet** [comment]
First pass by @stijnvanhoey, then @peterdesmet

**Comment by stijnvanhoey** [comment]
Figures updated and redundant sections excluded, all yours for revision @peterdesmet
